name: ci-pipeline

#on: [push]
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout to directory
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |                              # pipe is used to add more than one command.
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd app-code
        python -m pytest addition.py
